-- ============================================================
-- Migration 0001: Initial schema for NCPA Venue for Hire
-- ============================================================
-- SQLite (D1) compatible. All timestamps stored as ISO-8601 UTC strings.
-- Application renders in Asia/Kolkata. Currency INR.
-- IDs are TEXT (ULID-like) generated by the application layer.
-- ============================================================

-- ---- System / scheduler bookkeeping ----
CREATE TABLE IF NOT EXISTS scheduler_runs (
  id          INTEGER PRIMARY KEY AUTOINCREMENT,
  ran_at      TEXT NOT NULL,
  job         TEXT,
  note        TEXT,
  rows_affected INTEGER DEFAULT 0
);

-- ---- Application settings (admin-configurable; key/value) ----
-- Stores things like the Resend API key (encrypted), notification defaults, etc.
CREATE TABLE IF NOT EXISTS app_settings (
  key         TEXT PRIMARY KEY,
  value       TEXT,
  updated_at  TEXT NOT NULL,
  updated_by  TEXT
);

-- ---- Dropdown options (seeded from Dropdown_Master; admin-editable) ----
-- All lookup lists: venue, caterer, decorator, staff, status, enquiry_source, etc.
CREATE TABLE IF NOT EXISTS dropdown_options (
  id          TEXT PRIMARY KEY,
  list_key    TEXT NOT NULL,           -- e.g. 'venue', 'caterer', 'program_officer'
  value       TEXT NOT NULL,           -- the option label/value
  sort_order  INTEGER NOT NULL DEFAULT 0,
  is_active   INTEGER NOT NULL DEFAULT 1,
  metadata    TEXT,                    -- JSON: e.g. venue combos {parts: ["JBT","OAP"]}
  created_at  TEXT NOT NULL,
  UNIQUE(list_key, value)
);
CREATE INDEX IF NOT EXISTS idx_dropdown_list ON dropdown_options(list_key, is_active, sort_order);

-- ---- Checklist definitions (seeded from workbooks; admin can extend) ----
-- Defines the template items for Event Operations (14 sections) and Accounts (3 sections).
CREATE TABLE IF NOT EXISTS checklist_definitions (
  id            TEXT PRIMARY KEY,
  module        TEXT NOT NULL,         -- 'operations' | 'accounts'
  section       TEXT NOT NULL,         -- e.g. 'Financials', 'Confirmation Letter'
  field_key     TEXT NOT NULL,         -- stable identifier e.g. 'costing_email'
  label         TEXT NOT NULL,         -- display label
  field_type    TEXT NOT NULL,         -- text|textarea|number|date|dropdown|status|checkbox|computed
  options       TEXT,                  -- JSON array of allowed values (for dropdown/status)
  default_value TEXT,
  vfh_only      INTEGER NOT NULL DEFAULT 0,  -- shown only for VFH events
  is_computed   INTEGER NOT NULL DEFAULT 0,  -- read-only computed field
  triggers_task TEXT,                  -- JSON task-rule descriptor, nullable
  sort_order    INTEGER NOT NULL DEFAULT 0,
  created_at    TEXT NOT NULL,
  UNIQUE(module, field_key)
);
CREATE INDEX IF NOT EXISTS idx_checklist_def ON checklist_definitions(module, section, sort_order);

-- ---- Users & authentication ----
CREATE TABLE IF NOT EXISTS users (
  id                TEXT PRIMARY KEY,
  email             TEXT NOT NULL UNIQUE,
  name              TEXT NOT NULL,
  role              TEXT NOT NULL DEFAULT 'viewer',  -- admin|venue_manager|coordinator|viewer
  organisation      TEXT,                             -- department/vertical
  password_hash     TEXT NOT NULL,                    -- scrypt hash
  password_algo     TEXT NOT NULL DEFAULT 'scrypt',
  password_updated_at TEXT,
  -- TOTP MFA
  totp_secret       TEXT,          -- encrypted at rest; NULL if MFA not enrolled
  totp_enrolled_at  TEXT,
  -- Recovery codes (hashed, never stored in cleartext)
  recovery_codes    TEXT,          -- JSON array of hashed codes
  -- State
  is_active         INTEGER NOT NULL DEFAULT 1,
  is_archived       INTEGER NOT NULL DEFAULT 0,
  failed_logins     INTEGER NOT NULL DEFAULT 0,
  locked_until      TEXT,
  last_login_at     TEXT,
  created_at        TEXT NOT NULL,
  updated_at        TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);

-- ---- Sessions ----
CREATE TABLE IF NOT EXISTS sessions (
  id            TEXT PRIMARY KEY,        -- opaque session id
  user_id       TEXT NOT NULL REFERENCES users(id),
  csrf_token    TEXT NOT NULL,
  created_at    TEXT NOT NULL,
  expires_at    TEXT NOT NULL,
  ip_hint       TEXT,                    -- partial, never full IP in logs
  user_agent    TEXT,
  revoked_at    TEXT
);
CREATE INDEX IF NOT EXISTS idx_sessions_user ON sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_sessions_expires ON sessions(expires_at);

-- ---- Password reset tokens ----
CREATE TABLE IF NOT EXISTS password_resets (
  token_hash   TEXT PRIMARY KEY,
  user_id      TEXT NOT NULL REFERENCES users(id),
  expires_at   TEXT NOT NULL,
  used_at      TEXT,
  created_at   TEXT NOT NULL
);

-- ---- Audit log (system-level: auth, role changes, overrides, etc.) ----
CREATE TABLE IF NOT EXISTS audit_logs (
  id          TEXT PRIMARY KEY,
  actor_id    TEXT REFERENCES users(id),
  actor_email TEXT,
  action      TEXT NOT NULL,            -- e.g. 'auth.login', 'role.change', 'conflict.override'
  target_type TEXT,
  target_id   TEXT,
  detail      TEXT,                     -- JSON
  ip_hint     TEXT,
  created_at  TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_audit_target ON audit_logs(target_type, target_id);
CREATE INDEX IF NOT EXISTS idx_audit_actor ON audit_logs(actor_id, created_at);

-- ---- Organisations / clients ----
CREATE TABLE IF NOT EXISTS organisations (
  id            TEXT PRIMARY KEY,
  name          TEXT NOT NULL,
  org_type      TEXT,                   -- e.g. corporate, foundation, individual
  address       TEXT,
  gst_number    TEXT,
  pan_number    TEXT,
  tan_number    TEXT,
  bank_details  TEXT,                   -- JSON: {bank, account_name, account_no, ifsc, branch}
  notes         TEXT,
  is_archived   INTEGER NOT NULL DEFAULT 0,
  created_at    TEXT NOT NULL,
  updated_at    TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_org_name ON organisations(name);

-- ---- Contacts (1 org → many contacts) ----
CREATE TABLE IF NOT EXISTS contacts (
  id              TEXT PRIMARY KEY,
  organisation_id TEXT NOT NULL REFERENCES organisations(id),
  name            TEXT NOT NULL,
  role            TEXT,                 -- job title / role
  email           TEXT,
  phone           TEXT,
  is_primary      INTEGER NOT NULL DEFAULT 0,
  signing_authority INTEGER NOT NULL DEFAULT 0,
  courier_address TEXT,
  created_at      TEXT NOT NULL,
  updated_at      TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_contacts_org ON contacts(organisation_id);

-- ---- Events (master record) ----
CREATE TABLE IF NOT EXISTS events (
  id                  TEXT PRIMARY KEY,
  event_code          TEXT UNIQUE,     -- e.g. ENQ-MK_VS-0001 (seed) or generated
  title               TEXT NOT NULL,
  description         TEXT,
  organisation_id     TEXT REFERENCES organisations(id),
  primary_contact_id  TEXT REFERENCES contacts(id),
  -- Categorisation (dropdowns reference dropdown_options)
  event_type          TEXT,            -- EE | FR | VFH | Free Event
  hiring_category     TEXT,
  vertical            TEXT,
  program_officer     TEXT,            -- staff name (dropdown)
  event_owner         TEXT,            -- staff name (dropdown, "Handled By")
  collaboration_details TEXT,
  -- Dates (overall)
  event_start_date    TEXT,            -- ISO date (Asia/Kolkata semantics)
  event_end_date      TEXT,
  -- Status (event lifecycle state machine)
  status              TEXT NOT NULL DEFAULT 'draft',
  form_status         TEXT NOT NULL DEFAULT 'draft',  -- draft|published (form submission state)
  approval_status     TEXT,            -- not_required|pending|sent|received|approved
  confirmation_status TEXT,            -- none|made|couriered|signed_received
  -- Enquiry metadata
  enquiry_date        TEXT,
  enquiry_source      TEXT,
  repeat_client       INTEGER,
  priority            TEXT DEFAULT 'medium',
  -- Flexible/typed requirements JSON (Sound/Lighting/Stage/Recording/Green rooms/etc.)
  -- Structure enforced by TS types + Zod; stored as JSON text.
  requirements        TEXT,
  notes               TEXT,
  -- Completion rollups (computed by app; denormalised for fast display)
  ops_completion      REAL DEFAULT 0,  -- 0..1
  accounts_completion REAL DEFAULT 0,
  overall_completion  REAL DEFAULT 0,
  -- Lifecycle
  is_archived         INTEGER NOT NULL DEFAULT 0,
  created_by          TEXT REFERENCES users(id),
  created_at          TEXT NOT NULL,
  updated_at          TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_events_status ON events(status);
CREATE INDEX IF NOT EXISTS idx_events_dates ON events(event_start_date);
CREATE INDEX IF NOT EXISTS idx_events_org ON events(organisation_id);
CREATE INDEX IF NOT EXISTS idx_events_type ON events(event_type);

-- ---- Event status history (every transition) ----
CREATE TABLE IF NOT EXISTS event_status_history (
  id           TEXT PRIMARY KEY,
  event_id     TEXT NOT NULL REFERENCES events(id),
  from_status  TEXT,
  to_status    TEXT NOT NULL,
  changed_by   TEXT REFERENCES users(id),
  changed_at   TEXT NOT NULL,
  reason       TEXT,
  note         TEXT
);
CREATE INDEX IF NOT EXISTS idx_status_history_event ON event_status_history(event_id, changed_at);

-- ---- Venue bookings (1 event → many venue bookings) ----
CREATE TABLE IF NOT EXISTS venue_bookings (
  id              TEXT PRIMARY KEY,
  event_id        TEXT NOT NULL REFERENCES events(id),
  venue           TEXT NOT NULL,           -- venue name (dropdown)
  booking_status  TEXT NOT NULL DEFAULT 'tentative',  -- tentative|confirmed|cancelled
  number_of_shows INTEGER DEFAULT 1,
  -- Timings (per booking; granular per-date timings live in schedule_entries)
  ac_start        TEXT,
  ac_end          TEXT,
  event_duration_minutes INTEGER,
  -- Venue-specific requirements (JSON: lighting, stage, sound specific to this venue)
  requirements    TEXT,
  notes           TEXT,
  sort_order      INTEGER NOT NULL DEFAULT 0,
  created_at      TEXT NOT NULL,
  updated_at      TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_venue_bookings_event ON venue_bookings(event_id);
CREATE INDEX IF NOT EXISTS idx_venue_bookings_venue ON venue_bookings(venue);

-- ---- Schedule entries (1 venue booking → many schedule entries) ----
-- Activity types: Setup | Rehearsal | Show | Dismantling | Technical Meeting
CREATE TABLE IF NOT EXISTS schedule_entries (
  id              TEXT PRIMARY KEY,
  venue_booking_id TEXT NOT NULL REFERENCES venue_bookings(id),
  event_id        TEXT NOT NULL REFERENCES events(id),  -- denormalised for fast calendar queries
  activity_type   TEXT NOT NULL,   -- setup|rehearsal|show|dismantling|technical_meeting
  activity_date   TEXT NOT NULL,   -- ISO date
  start_time      TEXT,            -- HH:MM (IST)
  end_time        TEXT,            -- HH:MM (IST)
  notes           TEXT,
  sort_order      INTEGER NOT NULL DEFAULT 0,
  created_at      TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_schedule_event ON schedule_entries(event_id);
CREATE INDEX IF NOT EXISTS idx_schedule_venue ON schedule_entries(venue_booking_id);
CREATE INDEX IF NOT EXISTS idx_schedule_date ON schedule_entries(activity_date);

-- ---- Checklist items (per-event instance of checklist_definitions) ----
CREATE TABLE IF NOT EXISTS checklist_items (
  id              TEXT PRIMARY KEY,
  event_id        TEXT NOT NULL REFERENCES events(id),
  definition_id   TEXT NOT NULL REFERENCES checklist_definitions(id),
  module          TEXT NOT NULL,         -- denormalised from definition
  section         TEXT NOT NULL,
  field_key       TEXT NOT NULL,
  label           TEXT NOT NULL,
  status          TEXT NOT NULL DEFAULT 'not_started',  -- not_started|in_progress|completed|not_applicable|blocked
  value           TEXT,                  -- the stored answer (date string, dropdown value, etc.)
  due_date        TEXT,                  -- explicit date field (instalments, meetings, planned actions)
  completed_at    TEXT,
  completed_by    TEXT REFERENCES users(id),
  last_updated_at TEXT,
  last_updated_by TEXT REFERENCES users(id),
  UNIQUE(event_id, field_key)
);
CREATE INDEX IF NOT EXISTS idx_checklist_event ON checklist_items(event_id, module);

-- ---- Checklist corrections audit (authorised date corrections) ----
CREATE TABLE IF NOT EXISTS checklist_corrections (
  id          TEXT PRIMARY KEY,
  checklist_item_id TEXT NOT NULL REFERENCES checklist_items(id),
  old_value   TEXT,
  new_value   TEXT,
  corrected_by TEXT REFERENCES users(id),
  corrected_at TEXT NOT NULL,
  reason      TEXT NOT NULL
);

-- ---- Tasks (automatic or manual) ----
CREATE TABLE IF NOT EXISTS tasks (
  id                TEXT PRIMARY KEY,
  title             TEXT NOT NULL,
  description       TEXT,
  event_id          TEXT REFERENCES events(id),     -- optional
  venue_booking_id  TEXT REFERENCES venue_bookings(id), -- optional
  source_checklist_item_id TEXT REFERENCES checklist_items(id), -- optional
  task_type         TEXT NOT NULL DEFAULT 'manual',  -- automatic|manual
  source_rule       TEXT,                            -- e.g. 'approval_followup', 'instalment', 'confirmation_letter'
  idempotency_key   TEXT,                            -- dedupe key for automatic tasks
  assignee_id       TEXT REFERENCES users(id),
  due_date          TEXT,
  due_time          TEXT,
  priority          TEXT NOT NULL DEFAULT 'medium',  -- high|medium|low
  status            TEXT NOT NULL DEFAULT 'open',    -- open|in_progress|completed|cancelled
  completion_note   TEXT,
  completed_at      TEXT,
  completed_by      TEXT REFERENCES users(id),
  created_by        TEXT REFERENCES users(id),
  created_at        TEXT NOT NULL,
  updated_at        TEXT NOT NULL,
  UNIQUE(idempotency_key)
);
CREATE INDEX IF NOT EXISTS idx_tasks_event ON tasks(event_id);
CREATE INDEX IF NOT EXISTS idx_tasks_assignee ON tasks(assignee_id, status);
CREATE INDEX IF NOT EXISTS idx_tasks_due ON tasks(due_date, status);
CREATE INDEX IF NOT EXISTS idx_tasks_source ON tasks(source_rule, status);

-- ---- Notification rules (admin-configurable) ----
CREATE TABLE IF NOT EXISTS notification_rules (
  id              TEXT PRIMARY KEY,
  rule_name       TEXT NOT NULL,
  source_module   TEXT NOT NULL,        -- operations|accounts|task
  source_field    TEXT,                 -- field_key
  trigger_status  TEXT,                 -- value that triggers
  trigger_date_field TEXT,              -- date field to compute from
  interval_value  INTEGER,
  interval_unit   TEXT,                 -- hours|days|weeks
  channel         TEXT NOT NULL DEFAULT 'in_app', -- in_app|email|both
  recipient       TEXT,                 -- user id or role
  is_enabled      INTEGER NOT NULL DEFAULT 1,
  created_at      TEXT NOT NULL,
  updated_at      TEXT NOT NULL
);

-- ---- Notifications ----
CREATE TABLE IF NOT EXISTS notifications (
  id              TEXT PRIMARY KEY,
  idempotency_key TEXT UNIQUE,          -- duplicate-notification prevention
  recipient_id    TEXT REFERENCES users(id),
  recipient_role  TEXT,                 -- alternative: address a role
  title           TEXT NOT NULL,
  body            TEXT,
  channel         TEXT NOT NULL,        -- in_app|email
  related_event_id TEXT REFERENCES events(id),
  related_task_id TEXT REFERENCES tasks(id),
  is_read         INTEGER NOT NULL DEFAULT 0,
  -- Email delivery tracking
  email_status    TEXT,                 -- pending|sent|failed|skipped
  email_message_id TEXT,
  email_error     TEXT,
  sent_at         TEXT,
  created_at      TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_notifications_recipient ON notifications(recipient_id, is_read);
CREATE INDEX IF NOT EXISTS idx_notifications_event ON notifications(related_event_id);

-- ---- Documents (metadata in D1, file in R2) ----
CREATE TABLE IF NOT EXISTS documents (
  id            TEXT PRIMARY KEY,
  event_id      TEXT REFERENCES events(id),
  venue_booking_id TEXT REFERENCES venue_bookings(id),
  checklist_item_id TEXT REFERENCES checklist_items(id),
  file_name     TEXT NOT NULL,
  r2_key        TEXT NOT NULL,          -- R2 object key
  mime_type     TEXT,
  file_size     INTEGER,
  category      TEXT,                   -- inquiry|costing|approval|confirmation_letter|technical_rider|floor_plan|licence|accounts|tds_certificate|payment_advice|event_report|feedback|other
  uploaded_by   TEXT REFERENCES users(id),
  uploaded_at   TEXT NOT NULL,
  notes         TEXT
);
CREATE INDEX IF NOT EXISTS idx_documents_event ON documents(event_id);

-- ---- Event activity feed ----
CREATE TABLE IF NOT EXISTS event_activity (
  id          TEXT PRIMARY KEY,
  event_id    TEXT NOT NULL REFERENCES events(id),
  activity_type TEXT NOT NULL,          -- created|updated|status_changed|approval_sent|approval_received|document_uploaded|task_created|task_completed|checklist_updated|venue_added|venue_removed|confirmed|completed|closed|note_added
  detail      TEXT,                     -- JSON
  actor_id    TEXT REFERENCES users(id),
  created_at  TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_activity_event ON event_activity(event_id, created_at);

-- ---- Daily reports (immutable historical snapshots) ----
CREATE TABLE IF NOT EXISTS daily_reports (
  id            TEXT PRIMARY KEY,
  report_date   TEXT NOT NULL,
  generated_by  TEXT REFERENCES users(id),
  generated_at  TEXT NOT NULL,
  content       TEXT NOT NULL,          -- JSON snapshot of the full report
  notes         TEXT
);
CREATE INDEX IF NOT EXISTS idx_reports_date ON daily_reports(report_date);
